name = "escribus"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "firmas.tuperiodico.soy", custom_domain = true }
]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1


[[d1_databases]]
binding = "DB"
database_name = "lemma-db"
database_id = "16ec6c97-4c26-440f-8f27-2283ddc647c9"

# Secrets (configurados en el dashboard):
# - TELEGRAM_TOKEN
# - TELEGRAM_CHAT_ID
